### GET /
GET http://localhost:5000


###Register a user POST/Auth/Register
###
POST http://localhost:5000/auth/register
Content-Type: application/json

{
    "username" : "workera",
    "password" : "12541254"
}

###Login a user POST/Auth/login

###
POST http://localhost:5000/auth/login
Content-Type: application/json

{
    "username" : "workera",
    "password" : "12541254"
}


